### ISSUE TITLE
Consistency in 'speaking-grandma' lab and previous lesson

### ISSUE THREAD

**Issue by begreative** [learn-co-curriculum/speaking-grandma#12]
Hello! - Perhaps it was only , but I was a bit confused between how we were taught to output conditional statements in 'About Ruby conditionals' and its followup lab 'speaking-grandma'.

The original code I had written to solve for the lab was as follows:
```
def speak_to_grandma(phrase)
  if "#{phrase}" == "#{phrase}".upcase
    puts "NO, NOT SINCE 1938!"
  else
    puts "HUH?! SPEAK UP, SONNY!"
  end
end
```
Please note the **puts** in the above. When I would run the code in my terminal using ```ruby grandma.rb``` and try running the test manually (i.e copying and pasting the exact phrases directly from the ```grandma_spec.rb``` and running them as the method's argument), I'd get exactly the desired results. Because everything in the previous lesson required string output be prefaced with "puts" or "print", I thought this was necessary.

After nearly thirty minutes of trying to solve this, I finally tried it *without* the ```puts``` and as below:
```
def speak_to_grandma(phrase)
  if "#{phrase}" == "#{phrase}".upcase
    "NO, NOT SINCE 1938!"
  else
    "HUH?! SPEAK UP, SONNY!"
  end
end
```

This time it worked! (Yay!).

I'm just running this by you in case others are having similar issues between the examples in the previous lesson and the requirements to pass the test. I will definitely read the tests more carefully next time, as well.

Thanks and I hope this helps!

BeGreative

**Comment by AnnJohn** [comment]
Hi @begreative thanks for raising the issue. The reason why you can't use puts here is because we're looking for the return value to be the phrase. By using puts, the return value is nil. 

We do put this in parentheses in the Readme, but we'll look into making it more explicit. Thanks!
