### ISSUE TITLE
There are duplicate tests in the spec/grandma_spec.rb file.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/speaking-grandma#17]
I do not know if this was accidental or intentional, but the last two tests in the spec/grandma_spec.rb file are exact duplicates of the first two.

Sdcrouse

**Comment by morgvanny** [comment]
Strange we didn't notice this before. I just got rid of those, thank you.

**Comment by Sdcrouse** [comment]
You're welcome! Glad to help.
