### ISSUE TITLE
My IDE has not been functioning

### ISSUE THREAD

**Issue by pro-totype** [learn-co-curriculum/speaking-grandma#23]
This is what appears everytime I try to use IDE. However; Sandbox has been working.
What do I need to do? 
---------
[23:10:10] ~
// ♥ learn open speaking-grandma-onl01-seng-pt-052620
Looking for lesson...
Forking lesson...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Opening the lesson…please do not refresh the pageCloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
Cloning lesson...
Cannot clone this lesson right now. Please try again.
[23:10:22] ~
// ♥ [23:10:23] ~
// ♥ learn open speaking-grandma-onl01-seng-pt-052620
Looking for lesson...
Forking lesson...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Opening the lesson…please do not refresh the pageCloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
Cloning lesson...
Cannot clone this lesson right now. Please try again.
[23:10:32] ~
// ♥ [23:10:34] ~
// ♥ learn open speaking-grandma-onl01-seng-pt-052620
Looking for lesson...
Forking lesson...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Opening the lesson…please do not refresh the pageCloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
Cloning lesson...
Cannot clone this lesson right now. Please try again.
[23:10:44] ~
// ♥ [23:10:46] ~
// ♥ learn open speaking-grandma-onl01-seng-pt-052620
Looking for lesson...
Forking lesson...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Opening the lesson…please do not refresh the pageCloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
Cloning lesson...
Cannot clone this lesson right now. Please try again.
[23:10:56] ~
// ♥ [23:11:02] ~
// ♥ learn open speaking-grandma-onl01-seng-pt-052620
Looking for lesson...
Forking lesson...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Opening the lesson…please do not refresh the pageCloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
Cloning lesson...
Cannot clone this lesson right now. Please try again.
[23:11:12] ~
// ♥ [23:11:21] ~
// ♥ learn open speaking-grandma-onl01-seng-pt-052620
Looking for lesson...
Forking lesson...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Opening the lesson…please do not refresh the pageCloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
Unable to open the lesson…please move on to the next lessonCloning lesson...
Unable to open the lesson…please move on to the next lessonCannot clone this lesson right now. Please try again.
[23:11:30] ~
// ♥ Unable to open the lesson…please move on to the next lessonUnable to open the lesson…please move on to the next lesson[23:11:38] ~
// ♥ learn open speaking-grandma-onl01-seng-pt-052620
Looking for lesson...
Forking lesson...
Cloning lesson...
There was a problem cloning this lesson. Retrying...
Unable to open the lesson…please move on to the next lessonCloning lesson...
There was a problem cloning this lesson. Retrying...
Cloning lesson...
Cloning lesson...
Cannot clone this lesson right now. Please try again.
[23:11:48] ~
// ♥

**Comment by lizbur10** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

Thanks! 💙
